# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-PostalCode
version:      0.07
version_from: lib/Geo/PostalCode.pm
installdirs:  site
requires:
    File::Spec:                    0
    FileHandle:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
